---
kind: pipeline
type: kubernetes
name: compliance

steps:
  - name: pre-commit linter
    image: python:alpine
    commands:
      - apk add git go bash ruby
      - pip install pre-commit
      - pre-commit install --install-hooks
      - SKIP=hadolint pre-commit run --all-files
  - name: golang:1.19
    image: golang:1.19
    commands:
      - go get
      - gofmt -d -s .
      - go test -cover -failfast -timeout 2s ./...
