---
kind: pipeline
type: kubernetes
name: compliance

steps:
  - name: pre-commit linter
    image: python:alpine
    commands:
      - apk add git go bash ruby
      - pip install pre-commit
      - pre-commit install --install-hooks
      - SKIP=hadolint pre-commit run --all-files
  - name: golang:1.19
    image: golang:1.19
    commands:
      - go get
      - gofmt -d -s .
      - go test -cover -failfast -timeout 2s ./...
  - name: build docker image
    image: plugins/docker
    settings:
      repo: registry.cmj.tld/cmj/outage
      registry: registry.cmj.tld
      insecure: true
      purge: true
      tags:
        - latest
        - "${DRONE_COMMIT_SHA:0:8}"
  - name: deploy on server
    image: plugins/ansible:3
    environment:
      ANSIBLE_HOST_KEY_CHECKING: "False"
    settings:
      playbook: deployment/playbooks/upgrade.yml
      galaxy: deployment/playbooks/requirements.yml
      inventory: deployment/playbooks/inventory.ini
      galaxy_force: true
      user:
        from_secret: DEPLOY_USERNAME
      private_key:
        from_secret: DEPLOY_PRIVATE_KEY
