version: "3.7"

services:
  outage:
    image: registry.cmj.tld/cmj/outage
    platform: linux/amd64
    restart: always
    ports:
      - "127.0.0.1:9999:9999"
    volumes:
      - type: bind
        source: ./outage/conf.yml
        target: /outage/conf.yml
        read_only: true
